vich_uploader:
    db_driver: orm
    mappings:
        productos_fotos:
            uri_prefix:         '%app.path.productos_fotos%'
            upload_destination: '%kernel.project_dir%/public%app.path.productos_fotos%'

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
