<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKMEmxxi\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKMEmxxi/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerKMEmxxi.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerKMEmxxi\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerKMEmxxi\App_KernelProdContainer([
    'container.build_hash' => 'KMEmxxi',
    'container.build_id' => '42b30d80',
    'container.build_time' => 1653851380,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKMEmxxi');
