<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'admin' => [[], ['_controller' => 'App\\Controller\\Admin\\DashboardController::index'], [], [['text', '/admin']], [], [], []],
    'productosCat' => [['categoria'], ['_controller' => 'App\\Controller\\BaseController::productos'], [], [['variable', '/', '[^/]++', 'categoria', true], ['text', '/productos']], [], [], []],
    'detalles' => [['producto'], ['_controller' => 'App\\Controller\\BaseController::detalleProducto'], [], [['variable', '/', '[^/]++', 'producto', true], ['text', '/detalles']], [], [], []],
    'productos' => [[], ['_controller' => 'App\\Controller\\BaseController::productosGlobales'], [], [['text', '/productos']], [], [], []],
    'contacto' => [[], ['_controller' => 'App\\Controller\\BaseController::contacto'], [], [['text', '/contacto']], [], [], []],
    'adminProductos' => [[], ['_controller' => 'App\\Controller\\BaseController::administrarProductos'], [], [['text', '/adminProductos']], [], [], []],
    'adminCategorias' => [[], ['_controller' => 'App\\Controller\\BaseController::administrarCategorias'], [], [['text', '/adminCategorias']], [], [], []],
    'adminPedidos' => [[], ['_controller' => 'App\\Controller\\BaseController::administrarPedidos'], [], [['text', '/adminPedidos']], [], [], []],
    'pedidosProductos' => [['idPedido'], ['_controller' => 'App\\Controller\\BaseController::mostrarPedidosProductos'], [], [['variable', '/', '[^/]++', 'idPedido', true], ['text', '/pedidosProductos']], [], [], []],
    'anadir' => [['idProducto'], ['_controller' => 'App\\Controller\\BaseController::anadir'], [], [['variable', '/', '[^/]++', 'idProducto', true], ['text', '/anadir']], [], [], []],
    'cambiarUnidades' => [['idProducto'], ['_controller' => 'App\\Controller\\BaseController::cambiarUnidades'], [], [['variable', '/', '[^/]++', 'idProducto', true], ['text', '/cambiarUnidades']], [], [], []],
    'eliminarProductosCesta' => [['idProducto'], ['_controller' => 'App\\Controller\\BaseController::eliminarProductosCesta'], [], [['variable', '/', '[^/]++', 'idProducto', true], ['text', '/eliminarProductosCesta']], [], [], []],
    'completarPedido' => [['idPedido'], ['_controller' => 'App\\Controller\\BaseController::completarPedido'], [], [['variable', '/', '[^/]++', 'idPedido', true], ['text', '/completarPedido']], [], [], []],
    'resumenCesta' => [[], ['_controller' => 'App\\Controller\\BaseController::resumenCesta'], [], [['text', '/resumenCesta']], [], [], []],
    'cambiarUnidadesResumen' => [['idProducto'], ['_controller' => 'App\\Controller\\BaseController::cambiarUnidadesResumen'], [], [['variable', '/', '[^/]++', 'idProducto', true], ['text', '/cambiarUnidadesResumen']], [], [], []],
    'pedido' => [[], ['_controller' => 'App\\Controller\\BaseController::realizarPedido'], [], [['text', '/pedido']], [], [], []],
    'login' => [[], ['_controller' => 'App\\Controller\\LoginController::index'], [], [['text', '/login']], [], [], []],
    'app_productos_index' => [[], ['_controller' => 'App\\Controller\\ProductosController::index'], [], [['text', '/productosPrueba/']], [], [], []],
    'app_productos_new' => [[], ['_controller' => 'App\\Controller\\ProductosController::new'], [], [['text', '/productosPrueba/new']], [], [], []],
    'app_productos_show' => [['id'], ['_controller' => 'App\\Controller\\ProductosController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/productosPrueba']], [], [], []],
    'app_productos_edit' => [['id'], ['_controller' => 'App\\Controller\\ProductosController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/productosPrueba']], [], [], []],
    'app_productos_delete' => [['id'], ['_controller' => 'App\\Controller\\ProductosController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/productosPrueba']], [], [], []],
    'registro' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/registro']], [], [], []],
    'logout' => [[], [], [], [['text', '/logout']], [], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\BaseController::index'], [], [['text', '/']], [], [], []],
];
