<?php

namespace Container0GKAd44;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Yi027qSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Yi027qS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Yi027qS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\BaseController::administrarProductos' => ['privates', '.service_locator.G8FcB2Q', 'get_ServiceLocator_G8FcB2QService', true],
            'App\\Controller\\BaseController::anadir' => ['privates', '.service_locator.G8FcB2Q', 'get_ServiceLocator_G8FcB2QService', true],
            'App\\Controller\\BaseController::anadirProducto' => ['privates', '.service_locator.G8FcB2Q', 'get_ServiceLocator_G8FcB2QService', true],
            'App\\Controller\\BaseController::cambiarUnidades' => ['privates', '.service_locator.G8FcB2Q', 'get_ServiceLocator_G8FcB2QService', true],
            'App\\Controller\\BaseController::contacto' => ['privates', '.service_locator.G8FcB2Q', 'get_ServiceLocator_G8FcB2QService', true],
            'App\\Controller\\BaseController::detalleProducto' => ['privates', '.service_locator.G8FcB2Q', 'get_ServiceLocator_G8FcB2QService', true],
            'App\\Controller\\BaseController::eliminarProductos' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\BaseController::eliminarProductosCesta' => ['privates', '.service_locator.G8FcB2Q', 'get_ServiceLocator_G8FcB2QService', true],
            'App\\Controller\\BaseController::index' => ['privates', '.service_locator.G8FcB2Q', 'get_ServiceLocator_G8FcB2QService', true],
            'App\\Controller\\BaseController::productos' => ['privates', '.service_locator.G8FcB2Q', 'get_ServiceLocator_G8FcB2QService', true],
            'App\\Controller\\BaseController::productosGlobales' => ['privates', '.service_locator.G8FcB2Q', 'get_ServiceLocator_G8FcB2QService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.YU8H6ve', 'get_ServiceLocator_YU8H6veService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\BaseController:administrarProductos' => ['privates', '.service_locator.G8FcB2Q', 'get_ServiceLocator_G8FcB2QService', true],
            'App\\Controller\\BaseController:anadir' => ['privates', '.service_locator.G8FcB2Q', 'get_ServiceLocator_G8FcB2QService', true],
            'App\\Controller\\BaseController:anadirProducto' => ['privates', '.service_locator.G8FcB2Q', 'get_ServiceLocator_G8FcB2QService', true],
            'App\\Controller\\BaseController:cambiarUnidades' => ['privates', '.service_locator.G8FcB2Q', 'get_ServiceLocator_G8FcB2QService', true],
            'App\\Controller\\BaseController:contacto' => ['privates', '.service_locator.G8FcB2Q', 'get_ServiceLocator_G8FcB2QService', true],
            'App\\Controller\\BaseController:detalleProducto' => ['privates', '.service_locator.G8FcB2Q', 'get_ServiceLocator_G8FcB2QService', true],
            'App\\Controller\\BaseController:eliminarProductos' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\BaseController:eliminarProductosCesta' => ['privates', '.service_locator.G8FcB2Q', 'get_ServiceLocator_G8FcB2QService', true],
            'App\\Controller\\BaseController:index' => ['privates', '.service_locator.G8FcB2Q', 'get_ServiceLocator_G8FcB2QService', true],
            'App\\Controller\\BaseController:productos' => ['privates', '.service_locator.G8FcB2Q', 'get_ServiceLocator_G8FcB2QService', true],
            'App\\Controller\\BaseController:productosGlobales' => ['privates', '.service_locator.G8FcB2Q', 'get_ServiceLocator_G8FcB2QService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.YU8H6ve', 'get_ServiceLocator_YU8H6veService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\BaseController::administrarProductos' => '?',
            'App\\Controller\\BaseController::anadir' => '?',
            'App\\Controller\\BaseController::anadirProducto' => '?',
            'App\\Controller\\BaseController::cambiarUnidades' => '?',
            'App\\Controller\\BaseController::contacto' => '?',
            'App\\Controller\\BaseController::detalleProducto' => '?',
            'App\\Controller\\BaseController::eliminarProductos' => '?',
            'App\\Controller\\BaseController::eliminarProductosCesta' => '?',
            'App\\Controller\\BaseController::index' => '?',
            'App\\Controller\\BaseController::productos' => '?',
            'App\\Controller\\BaseController::productosGlobales' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\BaseController:administrarProductos' => '?',
            'App\\Controller\\BaseController:anadir' => '?',
            'App\\Controller\\BaseController:anadirProducto' => '?',
            'App\\Controller\\BaseController:cambiarUnidades' => '?',
            'App\\Controller\\BaseController:contacto' => '?',
            'App\\Controller\\BaseController:detalleProducto' => '?',
            'App\\Controller\\BaseController:eliminarProductos' => '?',
            'App\\Controller\\BaseController:eliminarProductosCesta' => '?',
            'App\\Controller\\BaseController:index' => '?',
            'App\\Controller\\BaseController:productos' => '?',
            'App\\Controller\\BaseController:productosGlobales' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
