<?php

namespace ContainerSxCvgj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBeforeEntityPersistedEventService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator..f8OXy2.EasyCorp\Bundle\EasyAdminBundle\Event\BeforeEntityPersistedEvent' shared service.
     *
     * @return \EasyCorp\Bundle\EasyAdminBundle\Event\BeforeEntityPersistedEvent
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator..f8OXy2": it references class "EasyCorp\\Bundle\\EasyAdminBundle\\Event\\BeforeEntityPersistedEvent" but no such service exists.');
    }
}
