<?php

namespace ContainerJFKDGY9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YXRTGfPService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.YXRTGfP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YXRTGfP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'producto' => ['privates', '.errored..service_locator.YXRTGfP.App\\Entity\\Productos', NULL, 'Cannot autowire service ".service_locator.YXRTGfP": it references class "App\\Entity\\Productos" but no such service exists.'],
            'productosRepository' => ['privates', 'App\\Repository\\ProductosRepository', 'getProductosRepositoryService', true],
        ], [
            'producto' => 'App\\Entity\\Productos',
            'productosRepository' => 'App\\Repository\\ProductosRepository',
        ]);
    }
}
