<?php

namespace ContainerJFKDGY9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPedidosProductoRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\PedidosProductoRepository' shared autowired service.
     *
     * @return \App\Repository\PedidosProductoRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\PedidosProductoRepository'] = new \App\Repository\PedidosProductoRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
