<?php

namespace ContainerJFKDGY9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductosTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\ProductosType' shared autowired service.
     *
     * @return \App\Form\ProductosType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\ProductosType'] = new \App\Form\ProductosType();
    }
}
