<?php

namespace ContainerKMEmxxi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductosControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\ProductosController' shared autowired service.
     *
     * @return \App\Controller\ProductosController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\ProductosController'] = $instance = new \App\Controller\ProductosController();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\ProductosController', $container));

        return $instance;
    }
}
