<?php

namespace ContainerKMEmxxi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductosService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.SWtO2pd.App\Entity\Productos' shared service.
     *
     * @return \App\Entity\Productos
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.SWtO2pd": it references class "App\\Entity\\Productos" but no such service exists.');
    }
}
