<?php

<<<<<<<< HEAD:var/cache/dev/ContainerSxCvgj8/getCestaCompraService.php
namespace ContainerSxCvgj8;
========
namespace ContainerTx0Fwkx;
>>>>>>>> 5f20a6994f46a2f8003b266fcce776d28f81e020:var/cache/dev/ContainerTx0Fwkx/getCestaCompraService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCestaCompraService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Controller\CestaCompra' shared autowired service.
     *
     * @return \App\Controller\CestaCompra
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'CestaCompra.php';

        return $container->privates['App\\Controller\\CestaCompra'] = new \App\Controller\CestaCompra(($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));
    }
}
