<?php

<<<<<<<< HEAD:var/cache/dev/ContainerSxCvgj8/getFiltersService.php
namespace ContainerSxCvgj8;
========
namespace ContainerTx0Fwkx;
>>>>>>>> 5f20a6994f46a2f8003b266fcce776d28f81e020:var/cache/dev/ContainerTx0Fwkx/getFiltersService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFiltersService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.OGjUKCt.EasyCorp\Bundle\EasyAdminBundle\Config\Filters' shared service.
     *
     * @return \EasyCorp\Bundle\EasyAdminBundle\Config\Filters
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.OGjUKCt": it references class "EasyCorp\\Bundle\\EasyAdminBundle\\Config\\Filters" but no such service exists.');
    }
}
