<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ0j6ZHS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ0j6ZHS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZ0j6ZHS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZ0j6ZHS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZ0j6ZHS\App_KernelDevDebugContainer([
    'container.build_hash' => 'Z0j6ZHS',
    'container.build_id' => 'c05d83ab',
    'container.build_time' => 1654519185,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ0j6ZHS');
