<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRxDSoEp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRxDSoEp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRxDSoEp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRxDSoEp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRxDSoEp\App_KernelDevDebugContainer([
    'container.build_hash' => 'RxDSoEp',
    'container.build_id' => '614630eb',
    'container.build_time' => 1652777264,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRxDSoEp');
