<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Productos extends \App\Entity\Productos implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Productos' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Productos' . "\0" . 'codigo', '' . "\0" . 'App\\Entity\\Productos' . "\0" . 'nombre', '' . "\0" . 'App\\Entity\\Productos' . "\0" . 'descripcion', '' . "\0" . 'App\\Entity\\Productos' . "\0" . 'pvp', '' . "\0" . 'App\\Entity\\Productos' . "\0" . 'imagen', '' . "\0" . 'App\\Entity\\Productos' . "\0" . 'rawImagen', '' . "\0" . 'App\\Entity\\Productos' . "\0" . 'foto', '' . "\0" . 'App\\Entity\\Productos' . "\0" . 'imageFile', '' . "\0" . 'App\\Entity\\Productos' . "\0" . 'pp', '' . "\0" . 'App\\Entity\\Productos' . "\0" . 'categoria', '' . "\0" . 'App\\Entity\\Productos' . "\0" . 'unidades', '' . "\0" . 'App\\Entity\\Productos' . "\0" . 'proveedor', '' . "\0" . 'App\\Entity\\Productos' . "\0" . 'productosPedidos'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Productos' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Productos' . "\0" . 'codigo', '' . "\0" . 'App\\Entity\\Productos' . "\0" . 'nombre', '' . "\0" . 'App\\Entity\\Productos' . "\0" . 'descripcion', '' . "\0" . 'App\\Entity\\Productos' . "\0" . 'pvp', '' . "\0" . 'App\\Entity\\Productos' . "\0" . 'imagen', '' . "\0" . 'App\\Entity\\Productos' . "\0" . 'rawImagen', '' . "\0" . 'App\\Entity\\Productos' . "\0" . 'foto', '' . "\0" . 'App\\Entity\\Productos' . "\0" . 'imageFile', '' . "\0" . 'App\\Entity\\Productos' . "\0" . 'pp', '' . "\0" . 'App\\Entity\\Productos' . "\0" . 'categoria', '' . "\0" . 'App\\Entity\\Productos' . "\0" . 'unidades', '' . "\0" . 'App\\Entity\\Productos' . "\0" . 'proveedor', '' . "\0" . 'App\\Entity\\Productos' . "\0" . 'productosPedidos'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Productos $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function displayImagen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'displayImagen', []);

        return parent::displayImagen();
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCodigo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigo', []);

        return parent::getCodigo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodigo(string $codigo): \App\Entity\Productos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigo', [$codigo]);

        return parent::setCodigo($codigo);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre(string $nombre): \App\Entity\Productos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', []);

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion(?string $descripcion): \App\Entity\Productos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', [$descripcion]);

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getPvp(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPvp', []);

        return parent::getPvp();
    }

    /**
     * {@inheritDoc}
     */
    public function setPvp(string $pvp): \App\Entity\Productos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPvp', [$pvp]);

        return parent::setPvp($pvp);
    }

    /**
     * {@inheritDoc}
     */
    public function getImagenCodificada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImagenCodificada', []);

        return parent::getImagenCodificada();
    }

    /**
     * {@inheritDoc}
     */
    public function getImagen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImagen', []);

        return parent::getImagen();
    }

    /**
     * {@inheritDoc}
     */
    public function setImagen($imagen): \App\Entity\Productos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImagen', [$imagen]);

        return parent::setImagen($imagen);
    }

    /**
     * {@inheritDoc}
     */
    public function getPp(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPp', []);

        return parent::getPp();
    }

    /**
     * {@inheritDoc}
     */
    public function setPp(string $pp): \App\Entity\Productos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPp', [$pp]);

        return parent::setPp($pp);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategoria(): ?\App\Entity\categoria
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategoria', []);

        return parent::getCategoria();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategoria(?\App\Entity\categoria $categoria): \App\Entity\Productos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategoria', [$categoria]);

        return parent::setCategoria($categoria);
    }

    /**
     * {@inheritDoc}
     */
    public function getUnidades(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnidades', []);

        return parent::getUnidades();
    }

    /**
     * {@inheritDoc}
     */
    public function setUnidades(int $unidades): \App\Entity\Productos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUnidades', [$unidades]);

        return parent::setUnidades($unidades);
    }

    /**
     * {@inheritDoc}
     */
    public function getProveedor(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProveedor', []);

        return parent::getProveedor();
    }

    /**
     * {@inheritDoc}
     */
    public function setProveedor(string $proveedor): \App\Entity\Productos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProveedor', [$proveedor]);

        return parent::setProveedor($proveedor);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductosPedidos(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductosPedidos', []);

        return parent::getProductosPedidos();
    }

    /**
     * {@inheritDoc}
     */
    public function addProductosPedido(\App\Entity\PedidosProducto $productosPedido): \App\Entity\Productos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProductosPedido', [$productosPedido]);

        return parent::addProductosPedido($productosPedido);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProductosPedido(\App\Entity\PedidosProducto $productosPedido): \App\Entity\Productos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProductosPedido', [$productosPedido]);

        return parent::removeProductosPedido($productosPedido);
    }

    /**
     * {@inheritDoc}
     */
    public function setImageFile(\Symfony\Component\HttpFoundation\File\File $foto = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageFile', [$foto]);

        return parent::setImageFile($foto);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageFile', []);

        return parent::getImageFile();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage($foto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', [$foto]);

        return parent::setImage($foto);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', []);

        return parent::getImage();
    }

}
